# Generated by Django 4.2.6 on 2024-06-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskT", "0002_category_remove_task_catagory_task_due_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="cat_id",
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="taskT.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taskT.user"
            ),
        ),
    ]
