# Generated by Django 4.2.6 on 2024-06-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskT", "0003_remove_category_cat_id_remove_task_cat_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="category",
            new_name="cat_id",
        ),
    ]
